name: ecommerce5_ui
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  google_sign_in: ^ 5.2.4
  firebase_core: ^1.13.1
  firebase_auth: "^3.3.11"
  cloud_firestore: "^3.1.10"
  flutter_facebook_auth: "^4.1.1"
  sqflite: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  status_change: ^2.0.0
  favorite_button: ^0.0.4
  carousel_pro: ^1.0.0
  loading: ^1.0.2
  flutter_rating_bar: ^4.0.0


dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/menu_icon/
    - assets/fonts/


  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Black.ttf
        - asset: assets/fonts/MontserratAlternates-Bold.ttf